/*\n  # Add GPS Tracking to Drivers\n\n  1. Changes\n    - Add `current_lat` column to drivers table for real-time latitude\n    - Add `current_long` column to drivers table for real-time longitude\n    - Add `last_gps_update` column to track when GPS was last updated\n    - Add `is_tracking` column to enable/disable GPS tracking per driver\n\n  2. Purpose\n    - Enable live GPS tracking of drivers in transit\n    - Support geofencing and auto-arrival detection\n    - Track location update timestamps for freshness validation\n*/\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'drivers' AND column_name = 'current_lat'\n  ) THEN\n    ALTER TABLE drivers ADD COLUMN current_lat double precision;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'drivers' AND column_name = 'current_long'\n  ) THEN\n    ALTER TABLE drivers ADD COLUMN current_long double precision;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'drivers' AND column_name = 'last_gps_update'\n  ) THEN\n    ALTER TABLE drivers ADD COLUMN last_gps_update timestamptz;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'drivers' AND column_name = 'is_tracking'\n  ) THEN\n    ALTER TABLE drivers ADD COLUMN is_tracking boolean DEFAULT false;
\n  END IF;
\nEND $$;
\n\n-- Create index for faster GPS queries\nCREATE INDEX IF NOT EXISTS idx_drivers_gps ON drivers(current_lat, current_long) WHERE current_lat IS NOT NULL AND current_long IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_drivers_tracking ON drivers(is_tracking) WHERE is_tracking = true;
\n;
